name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  html-validate:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate HTML files
        uses: wemakeservices/html-validate-action@v0.1.6
        with:
          files: "*.html"

  check-links:
    name: Check for broken links and images
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check links and images
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --exclude-mail
            './**/*.html'
          fail: true
